# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\prana\Desktop\Documents\My Files\Programming\To Trash Or Not To Trash\my_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 1141)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.window = QtWidgets.QFrame(self.centralwidget)
        self.window.setGeometry(QtCore.QRect(10, 20, 691, 471))
        self.window.setStyleSheet("QFrame {\n"
"    background-color: rgb(247, 254, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window.setObjectName("window")
        self.easter_egg = QtWidgets.QPushButton(self.window)
        self.easter_egg.setGeometry(QtCore.QRect(0, 350, 21, 21))
        self.easter_egg.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font: 15pt \"Onyx\";\n"
"    text-align:center;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(231, 231, 231);\n"
"}")
        self.easter_egg.setText("")
        self.easter_egg.setObjectName("easter_egg")
        self.title_bar = QtWidgets.QLabel(self.window)
        self.title_bar.setGeometry(QtCore.QRect(0, 0, 691, 41))
        self.title_bar.setStyleSheet("QLabel {\n"
"    background-color: rgb(242, 250, 248);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 148, 148);\n"
"    qproperty-alignment: AlignCenter;\n"
"    padding-bottom: 2px;\n"
"    font: 12pt \"Cascadia Code\";\n"
"}")
        self.title_bar.setObjectName("title_bar")
        self.btn_close = QtWidgets.QPushButton(self.window)
        self.btn_close.setGeometry(QtCore.QRect(10, 12, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 96, 92);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(221, 82, 80);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setAutoDefault(False)
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.window)
        self.btn_minimize.setGeometry(QtCore.QRect(42, 12, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    \n"
"    background-color:rgb(255, 189, 68);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(225, 164, 60);\n"
"}\n"
"QPushButton:!enabled {\n"
"  color:rgb(218, 218, 218);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setAutoDefault(False)
        self.btn_minimize.setObjectName("btn_minimize")
        self.remaining_items = QtWidgets.QPushButton(self.window)
        self.remaining_items.setGeometry(QtCore.QRect(20, 330, 121, 91))
        self.remaining_items.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    font: 10pt \"Cascadia Code\";\n"
"    background-color: rgb(116, 195, 255);\n"
"    color: rgb(243, 243, 243);\n"
"}")
        self.remaining_items.setObjectName("remaining_items")
        self.stats = QtWidgets.QPushButton(self.window)
        self.stats.setGeometry(QtCore.QRect(210, 110, 271, 181))
        self.stats.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font: 16pt \"Dongle\";\n"
"    \n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"")
        self.stats.setObjectName("stats")
        self.timer = QtWidgets.QPushButton(self.window)
        self.timer.setGeometry(QtCore.QRect(550, 340, 121, 71))
        self.timer.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 15px;\n"
"    font: 14pt \"Modern No. 20\";\n"
"    color: rgb(56, 56, 56);\n"
"    background-color: rgb(172, 224, 255);\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(152, 198, 225);\n"
"}")
        self.timer.setObjectName("timer")
        self.item = QtWidgets.QGraphicsView(self.window)
        self.item.setGeometry(QtCore.QRect(160, 300, 371, 151))
        self.item.setStyleSheet("background-color: rgb(243, 255, 235);")
        self.item.setObjectName("item")
        self.box11 = QtWidgets.QPushButton(self.window)
        self.box11.setGeometry(QtCore.QRect(240, 50, 211, 51))
        self.box11.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font: 14pt \"Cascadia Code\";    \n"
"}")
        self.box11.setObjectName("box11")
        self.recycle = QtWidgets.QPushButton(self.window)
        self.recycle.setGeometry(QtCore.QRect(500, 110, 171, 161))
        self.recycle.setStyleSheet("QPushButton {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(239, 255, 246);\n"
"    color: #224168;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 25 28pt \"Cascadia Code Light\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(213, 227, 219);\n"
"}\n"
"")
        self.recycle.setObjectName("recycle")
        self.trashcan = QtWidgets.QPushButton(self.window)
        self.trashcan.setGeometry(QtCore.QRect(20, 110, 171, 161))
        self.trashcan.setStyleSheet("QPushButton {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(225, 232, 232);\n"
"    color: #224168;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 25 25pt \"Cascadia Code Light\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(197, 202, 202);\n"
"}")
        self.trashcan.setObjectName("trashcan")
        self.btn_disabled_3 = QtWidgets.QPushButton(self.window)
        self.btn_disabled_3.setGeometry(QtCore.QRect(74, 12, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_disabled_3.sizePolicy().hasHeightForWidth())
        self.btn_disabled_3.setSizePolicy(sizePolicy)
        self.btn_disabled_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(218, 218, 218);\n"
"}")
        self.btn_disabled_3.setText("")
        self.btn_disabled_3.setAutoDefault(False)
        self.btn_disabled_3.setObjectName("btn_disabled_3")
        self.popup = QtWidgets.QFrame(self.centralwidget)
        self.popup.setGeometry(QtCore.QRect(20, 510, 671, 381))
        self.popup.setStyleSheet("QFrame {\n"
"    background-color: rgb(247, 254, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.popup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.popup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.popup.setObjectName("popup")
        self.help_bar = QtWidgets.QLabel(self.popup)
        self.help_bar.setGeometry(QtCore.QRect(0, 0, 671, 41))
        self.help_bar.setStyleSheet("QLabel {\n"
"    background-color: rgb(242, 250, 248);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 148, 148);\n"
"    qproperty-alignment: AlignCenter;\n"
"    padding-bottom: 2px;\n"
"    font: 12pt \"Cascadia Code\";\n"
"}")
        self.help_bar.setObjectName("help_bar")
        self.btn_close_popup = QtWidgets.QPushButton(self.popup)
        self.btn_close_popup.setGeometry(QtCore.QRect(10, 12, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_popup.sizePolicy().hasHeightForWidth())
        self.btn_close_popup.setSizePolicy(sizePolicy)
        self.btn_close_popup.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 96, 92);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(221, 82, 80);\n"
"}")
        self.btn_close_popup.setText("")
        self.btn_close_popup.setAutoDefault(False)
        self.btn_close_popup.setObjectName("btn_close_popup")
        self.btn_disabled = QtWidgets.QPushButton(self.popup)
        self.btn_disabled.setGeometry(QtCore.QRect(74, 12, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_disabled.sizePolicy().hasHeightForWidth())
        self.btn_disabled.setSizePolicy(sizePolicy)
        self.btn_disabled.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(218, 218, 218);\n"
"}")
        self.btn_disabled.setText("")
        self.btn_disabled.setAutoDefault(False)
        self.btn_disabled.setObjectName("btn_disabled")
        self.btn_minimize_2 = QtWidgets.QPushButton(self.popup)
        self.btn_minimize_2.setGeometry(QtCore.QRect(42, 12, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize_2.sizePolicy().hasHeightForWidth())
        self.btn_minimize_2.setSizePolicy(sizePolicy)
        self.btn_minimize_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(218, 218, 218);\n"
"}")
        self.btn_minimize_2.setText("")
        self.btn_minimize_2.setAutoDefault(False)
        self.btn_minimize_2.setObjectName("btn_minimize_2")
        self.text = QtWidgets.QPushButton(self.popup)
        self.text.setGeometry(QtCore.QRect(0, 60, 671, 51))
        self.text.setStyleSheet("QPushButton{\n"
"    font: 22pt \"Algerian\";\n"
"    border:none;\n"
"    border-radius: 8px;    \n"
"    background-color: #f7feff;\n"
"}")
        self.text.setObjectName("text")
        self.text_2 = QtWidgets.QPushButton(self.popup)
        self.text_2.setGeometry(QtCore.QRect(0, 120, 671, 101))
        self.text_2.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 8pt \"Nirmala UI\";\n"
"    border:none;\n"
"    border-radius: 8px;    \n"
"    background-color: #f7feff;\n"
"}")
        self.text_2.setObjectName("text_2")
        self.text_5 = QtWidgets.QPushButton(self.popup)
        self.text_5.setGeometry(QtCore.QRect(50, 290, 91, 51))
        self.text_5.setStyleSheet("QPushButton {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(225, 232, 232);\n"
"    color: #224168;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 25 14pt \"Cascadia Code Light\";\n"
"    qproperty-alignment: Left;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(197, 202, 202);\n"
"}")
        self.text_5.setObjectName("text_5")
        self.text_3 = QtWidgets.QPushButton(self.popup)
        self.text_3.setGeometry(QtCore.QRect(50, 250, 91, 31))
        self.text_3.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 7.5pt \"Nirmala UI\";\n"
"    border:none;\n"
"    border-radius: 8px;    \n"
"    background-color: #f7feff;\n"
"}")
        self.text_3.setObjectName("text_3")
        self.text_15 = QtWidgets.QPushButton(self.popup)
        self.text_15.setGeometry(QtCore.QRect(170, 290, 91, 51))
        self.text_15.setStyleSheet("QPushButton {\n"
"    border-radius: 3px;\n"
"    background-color: rgb(239, 255, 246);\n"
"    color: #224168;\n"
"    padding: 2px;\n"
"    padding-bottom: 5px;    \n"
"    font: 25 14pt \"Cascadia Code Light\";\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(213, 227, 219);\n"
"}\n"
"\n"
"")
        self.text_15.setObjectName("text_15")
        self.text_9 = QtWidgets.QPushButton(self.popup)
        self.text_9.setGeometry(QtCore.QRect(290, 290, 91, 51))
        self.text_9.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 5px;\n"
"    font: 8pt \"Cascadia Code\";\n"
"    background-color: rgb(116, 195, 255);\n"
"    color: rgb(243, 243, 243);\n"
"}")
        self.text_9.setObjectName("text_9")
        self.text_6 = QtWidgets.QPushButton(self.popup)
        self.text_6.setGeometry(QtCore.QRect(290, 240, 91, 41))
        self.text_6.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 7.5pt \"Nirmala UI\";\n"
"    border:none;\n"
"    border-radius: 8px;    \n"
"    background-color: #f7feff;\n"
"}")
        self.text_6.setObjectName("text_6")
        self.text_104 = QtWidgets.QPushButton(self.popup)
        self.text_104.setGeometry(QtCore.QRect(410, 290, 91, 51))
        self.text_104.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 3px;\n"
"    font: 10pt \"Modern No. 20\";\n"
"    color: rgb(56, 56, 56);\n"
"    background-color: rgb(172, 224, 255);\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(152, 198, 225);\n"
"}")
        self.text_104.setObjectName("text_104")
        self.text_10 = QtWidgets.QPushButton(self.popup)
        self.text_10.setGeometry(QtCore.QRect(170, 250, 91, 31))
        self.text_10.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 7.5pt \"Nirmala UI\";\n"
"    border:none;\n"
"    border-radius: 8px;    \n"
"    background-color: #f7feff;\n"
"}")
        self.text_10.setObjectName("text_10")
        self.text_13 = QtWidgets.QPushButton(self.popup)
        self.text_13.setGeometry(QtCore.QRect(530, 290, 91, 51))
        self.text_13.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 3px;\n"
"    font: 16pt \"Dongle\";\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"")
        self.text_13.setObjectName("text_13")
        self.text_12 = QtWidgets.QPushButton(self.popup)
        self.text_12.setGeometry(QtCore.QRect(530, 250, 91, 31))
        self.text_12.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 7.5pt \"Nirmala UI\";\n"
"    border:none;\n"
"    border-radius: 8px;    \n"
"    background-color: #f7feff;\n"
"}")
        self.text_12.setObjectName("text_12")
        self.text_7 = QtWidgets.QPushButton(self.popup)
        self.text_7.setGeometry(QtCore.QRect(410, 240, 91, 41))
        self.text_7.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 7.5pt \"Nirmala UI\";\n"
"    border:none;\n"
"    border-radius: 8px;    \n"
"    background-color: #f7feff;\n"
"}")
        self.text_7.setObjectName("text_7")
        self.popup_2 = QtWidgets.QFrame(self.centralwidget)
        self.popup_2.setGeometry(QtCore.QRect(10, 910, 511, 231))
        self.popup_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(247, 254, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.popup_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.popup_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.popup_2.setObjectName("popup_2")
        self.easter_egg_3 = QtWidgets.QPushButton(self.popup_2)
        self.easter_egg_3.setGeometry(QtCore.QRect(0, 350, 21, 21))
        self.easter_egg_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font: 15pt \"Onyx\";\n"
"    text-align:center;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(231, 231, 231);\n"
"}")
        self.easter_egg_3.setText("")
        self.easter_egg_3.setObjectName("easter_egg_3")
        self.help_bar_2 = QtWidgets.QLabel(self.popup_2)
        self.help_bar_2.setGeometry(QtCore.QRect(0, 0, 511, 41))
        self.help_bar_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(242, 250, 248);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 148, 148);\n"
"    qproperty-alignment: AlignCenter;\n"
"    padding-bottom: 2px;\n"
"    font: 12pt \"Cascadia Code\";\n"
"}")
        self.help_bar_2.setObjectName("help_bar_2")
        self.btn_close_note = QtWidgets.QPushButton(self.popup_2)
        self.btn_close_note.setGeometry(QtCore.QRect(10, 12, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_note.sizePolicy().hasHeightForWidth())
        self.btn_close_note.setSizePolicy(sizePolicy)
        self.btn_close_note.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 96, 92);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(221, 82, 80);\n"
"}")
        self.btn_close_note.setText("")
        self.btn_close_note.setAutoDefault(False)
        self.btn_close_note.setObjectName("btn_close_note")
        self.btn_disabled_2 = QtWidgets.QPushButton(self.popup_2)
        self.btn_disabled_2.setGeometry(QtCore.QRect(74, 12, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_disabled_2.sizePolicy().hasHeightForWidth())
        self.btn_disabled_2.setSizePolicy(sizePolicy)
        self.btn_disabled_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(218, 218, 218);\n"
"}")
        self.btn_disabled_2.setText("")
        self.btn_disabled_2.setAutoDefault(False)
        self.btn_disabled_2.setObjectName("btn_disabled_2")
        self.btn_minimize_3 = QtWidgets.QPushButton(self.popup_2)
        self.btn_minimize_3.setGeometry(QtCore.QRect(42, 12, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize_3.sizePolicy().hasHeightForWidth())
        self.btn_minimize_3.setSizePolicy(sizePolicy)
        self.btn_minimize_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(218, 218, 218);\n"
"}")
        self.btn_minimize_3.setText("")
        self.btn_minimize_3.setAutoDefault(False)
        self.btn_minimize_3.setObjectName("btn_minimize_3")
        self.text_8 = QtWidgets.QPushButton(self.popup_2)
        self.text_8.setGeometry(QtCore.QRect(0, 50, 511, 171))
        self.text_8.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 9.5pt \"Nirmala UI\";\n"
"    border:none;\n"
"    border-radius: 8px;    \n"
"    background-color: #f7feff;\n"
"}")
        self.text_8.setObjectName("text_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_bar.setText(_translate("MainWindow", "To Trash Or Not To Trash"))
        self.remaining_items.setText(_translate("MainWindow", "Remaining\n"
"##"))
        self.stats.setText(_translate("MainWindow", "Round:\n"
"Correct:\n"
"Wrong:\n"
"Accuracy:\n"
"Score:"))
        self.timer.setText(_translate("MainWindow", "Begin?"))
        self.box11.setText(_translate("MainWindow", "Stats"))
        self.recycle.setText(_translate("MainWindow", "♻"))
        self.trashcan.setText(_translate("MainWindow", "🗑"))
        self.help_bar.setText(_translate("MainWindow", "Welcome"))
        self.text.setText(_translate("MainWindow", "To Trash Or Not To Trash"))
        self.text_2.setText(_translate("MainWindow", "Welcome. In this game, you decide whether to throw an item in the trash or recycle it.\n"
"There will be multiple timed rounds where you will throw away as many items as possible.\n"
"If you finish before time is called, you will recieve bonus points.\n"
"But be wary of your accuracy, for it will affect your final score..."))
        self.text_5.setText(_translate("MainWindow", "🗑"))
        self.text_3.setText(_translate("MainWindow", "Trashcan"))
        self.text_15.setText(_translate("MainWindow", "♻"))
        self.text_9.setText(_translate("MainWindow", "Remaining"))
        self.text_6.setText(_translate("MainWindow", "Remaining\n"
"Items"))
        self.text_104.setText(_translate("MainWindow", "Begin?"))
        self.text_10.setText(_translate("MainWindow", "Recycle Bin"))
        self.text_13.setText(_translate("MainWindow", "Score"))
        self.text_12.setText(_translate("MainWindow", "User Stats"))
        self.text_7.setText(_translate("MainWindow", "Begin Game\n"
"Timer"))
        self.help_bar_2.setText(_translate("MainWindow", "Note"))
        self.text_8.setText(_translate("MainWindow", "If you are seeing this, then something went wrong. Please report this bug as\n"
"Error 156. Thank you for your support."))
